name: Deploy to Hostinger

on:
  push:
    branches:
      - master # Or 'main', depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a standard Linux runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --- Frontend Build ---
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Specify your Node.js version

    - name: Clean npm cache
      working-directory: ./notesvault-react-mvp
      run: npm cache clean --force

    - name: Install Frontend Dependencies (Clean Install)
      working-directory: ./notesvault-react-mvp # Specify frontend directory
      run: npm ci # Use clean install based on package-lock.json

    - name: Remove previous build output
      working-directory: ./notesvault-react-mvp
      run: rm -rf dist # Ensure a completely fresh build

    - name: Build Frontend
      working-directory: ./notesvault-react-mvp # Specify frontend directory
      env: # Set environment variables for this step
        VITE_API_BASE_URL: /api
      # The run command now uses the environment variable set above
      run: npm run build
      # Note: We use /api assuming PHP scripts are in public_html/api
      # If your final PHP API URL is different, adjust this build command accordingly.

    # --- Prepare Deployment Files ---
    # Create a temporary directory to gather all files for deployment
    - name: Create deployment package directory
      run: mkdir deployment_package

    # Copy built frontend files into a 'notesvault' subdirectory
    - name: Copy frontend build to deployment package root
      run: cp -r ./notesvault-react-mvp/dist/* ./deployment_package/

    # Copy PHP API files
    - name: Copy PHP API to deployment package
      run: cp -r ./api ./deployment_package/


    # Copy .htaccess file
    - name: Copy .htaccess to deployment package
      run: cp ./.htaccess ./deployment_package/

    # --- Configure PHP Database ---
    # Replace placeholders in config.php with secrets
    # IMPORTANT: Ensure config.php in repo uses distinct placeholders
    - name: Configure api/config.php
      env:
        DB_HOST_SECRET: ${{ secrets.DB_HOST }}
        DB_USER_SECRET: ${{ secrets.DB_USER }}
        DB_PASS_SECRET: ${{ secrets.DB_PASS }}
        DB_NAME_SECRET: ${{ secrets.DB_NAME }}
        JWT_SECRET_KEY_SECRET: ${{ secrets.JWT_SECRET_KEY }}
      run: |
        sed -i "s|define('DB_HOST', '.*');|define('DB_HOST', '$DB_HOST_SECRET');|g" ./deployment_package/api/config.php
        sed -i "s|define('DB_USER', '.*');|define('DB_USER', '$DB_USER_SECRET');|g" ./deployment_package/api/config.php
        sed -i "s|define('DB_PASS', '.*');|define('DB_PASS', '$DB_PASS_SECRET');|g" ./deployment_package/api/config.php
        sed -i "s|define('DB_NAME', '.*');|define('DB_NAME', '$DB_NAME_SECRET');|g" ./deployment_package/api/config.php
        sed -i "s|define('JWT_SECRET_KEY', '.*');|define('JWT_SECRET_KEY', '$JWT_SECRET_KEY_SECRET');|g" ./deployment_package/api/config.php

        # Add sed command for frontend URL if needed in config.php

    # --- Deploy React App via FTP (No Clean Slate, Exclude API) --- # Force redeploy
    - name: FTP Deploy React App
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_SERVER }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        local-dir: ./deployment_package/ # Source is the root of the package
        server-dir: /public_html/ # Target the web root
        # No exclude needed, deploying the whole package

        # dangerous-clean-slate: true # Avoid clean slate to prevent deletion errors
