name: Deploy to Hostinger

on:
  push:
    branches:
      - master # Or your main deployment branch (e.g., main)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use an appropriate LTS version

    - name: Install Frontend Dependencies
      run: npm ci
      working-directory: ./notesvault-react-mvp

    - name: Build React App # Output goes to notesvault-react-mvp/dist
      run: npm run build
      working-directory: ./notesvault-react-mvp

    - name: Deploy Project Files to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_SERVER }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        protocol: ftp # Or ftps, sftp depending on your Hostinger setup
        port: 21 # Default FTP port, change if needed (e.g., 22 for SFTP)
        local-dir: ./ # Deploy from the project root
        server-dir: /public_html/ # Deploy to public_html on server
        # IMPORTANT: Ensure dangerous-clean-slate is false or omitted (default is false)
        exclude: | # Exclude patterns relative to local-dir (project root)
          **/.git*
          **/.git*/**
          **/.github/**
          **/node_modules/**
          ./notesvault-react-mvp/src/**
          ./notesvault-react-mvp/public/**
          ./notesvault-react-mvp/node_modules/**
          ./notesvault-react-mvp/.gitignore
          ./notesvault-react-mvp/package.json
          ./notesvault-react-mvp/package-lock.json
          ./notesvault-react-mvp/tsconfig.json
          ./notesvault-react-mvp/tsconfig.app.json
          ./notesvault-react-mvp/tsconfig.node.json
          ./notesvault-react-mvp/vite.config.ts
          ./notesvault-react-mvp/README.md
          ./notesvault-react-mvp/postcss.config.cjs
          ./notesvault-react-mvp/tailwind.config.js
          ./notesvault-react-mvp/eslint.config.js
          ./api/config.prod.php # Prevent accidental upload if it exists locally
          ./api/logs/**
          ./backend/** # Exclude python backend if not needed on Hostinger
          ./Architecture/**
          ./Features/**
          ./Finance/**
          ./mvp_document_generator/**
          ./MVP_Planning/**
          ./Planning/**
          ./Process/**
          ./Technology/**
          ./README.md
          ./vercel.json # Not needed for Hostinger
          ./JWT_SECRET_KEY # Should be ignored by .gitignore anyway, but good to be explicit
          # Add any other files/dirs not needed on the server
