name: Deploy to Hostinger

on:
  push:
    branches:
      - master # Or your main deployment branch (e.g., main)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use an appropriate LTS version

    - name: Install Frontend Dependencies
      run: npm ci
      working-directory: ./notesvault-react-mvp

    - name: Build React App
      run: npm run build
      working-directory: ./notesvault-react-mvp

    - name: Copy .htaccess to dist folder
      run: cp .htaccess ./notesvault-react-mvp/dist/

    - name: Deploy Frontend + .htaccess to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_SERVER }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        protocol: ftp # Or ftps, sftp depending on your Hostinger setup
        port: 21 # Default FTP port, change if needed (e.g., 22 for SFTP)
        local-dir: ./notesvault-react-mvp/dist/ # Source directory (now includes .htaccess)
        server-dir: /public_html/ # Destination base directory on server
        # Use dangerous-clean-slate: true if you want the action to remove files
        # on the server that are NOT in the local-dir being uploaded.
        # USE WITH CAUTION as it can delete unexpected files if paths are wrong.
        # dangerous-clean-slate: true
        exclude: | # Exclude patterns relative to local-dir
          **/.git*
          **/.git*/**
          **/node_modules/**

    - name: Deploy API to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_SERVER }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        protocol: ftp # Or ftps, sftp depending on your Hostinger setup
        port: 21 # Default FTP port, change if needed (e.g., 22 for SFTP)
        local-dir: ./api/ # Source directory
        server-dir: /public_html/api/ # Destination directory on server
        exclude: | # Exclude patterns relative to local-dir
          **/config.prod.php
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/logs/** # Exclude logs directory if present
